### ISSUE TITLE
Upgrade Spring Boot to the latest version

### ISSUE THREAD

**Issue by Buzzardo** [spring-guides/gs-spring-cloud-loadbalancer#13]
Update the guide to use the most recent Spring Boot version.

To do so, change the Spring Boot version in:

initial/build.gradle
initial/pom.xml
complete/build.gradle
complete/pom.xml

**Comment by daisukehanamura** [comment]
Hi, I am an engineer working for an IT company in Japan.
This is my first time to contribute to OSS.

I will update my springboot version to 3.1.5.
I checked the latest version from the official hp.
https://spring.io/projects/spring-boot#learn

I sent a PR after I confirmed that the test was successful.
Please check if there is any problem！

**Comment by Buzzardo** [comment]
You did it right, and I have merged it.  Welcome to the world of OSS. :)
